<?php

namespace UrlReducer\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository {
	/**
	 * Returns number of rows
	 */
	public function count() {
		return $this->createQueryBuilder('1')
		 ->select('COUNT(1)')
		 ->getQuery()
		 ->getSingleScalarResult();
	}
}
