url_reducer_core_phpinfo:
    pattern:  /phpinfo
    defaults: { _controller: UrlReducerCoreBundle:Default:phpinfo }

url_reducer_core_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UrlReducerCoreBundle:Default:index }

url_reducer_core_url_generate:
    pattern:  /
    defaults: { _controller: UrlReducerCoreBundle:Url:generateReducedUrl }

url_reducer_core_url_delete:
    pattern:  /url/delete
    defaults: { _controller: UrlReducerCoreBundle:Url:delete }

url_reducer_core_user_login:
    pattern:  /login
    defaults: { _controller: UrlReducerCoreBundle:User:login }

url_reducer_core_user_logout:
    pattern:  /logout
    defaults: { _controller: UrlReducerCoreBundle:User:logout }

url_reducer_core_user_register:
    pattern:  /register
    defaults: { _controller: UrlReducerCoreBundle:User:register }
#
url_reducer_core_user_menu:
    pattern:  /user/menu
    defaults: { _controller: UrlReducerCoreBundle:User:userMenu }

url_reducer_core_member_menu:
    pattern:  /member/menu
    defaults: { _controller: UrlReducerCoreBundle:User:memberMenu }

# Must be the last route declared to not match each static urls
url_reducer_core_url_go:
    pattern:  /{sUrl}
    defaults: { _controller: UrlReducerCoreBundle:Url:goToSourceUrl }

