url_reducer_core_phpinfo:
    pattern:  /phpinfo
    defaults: { _controller: UrlReducerCoreBundle:Default:phpinfo }

url_reducer_core_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UrlReducerCoreBundle:Default:index }

url_reducer_core_url_generate:
    pattern:  /
    defaults: { _controller: UrlReducerCoreBundle:Url:generateReducedUrl }

url_reducer_core_url_delete:
    pattern:  /url/delete
    defaults: { _controller: UrlReducerCoreBundle:Url:delete }

url_reducer_core_member_login:
    pattern:  /login
    defaults: { _controller: UrlReducerCoreBundle:Member:login }

url_reducer_core_member_logout:
    pattern:  /logout
    defaults: { _controller: UrlReducerCoreBundle:Member:logout }

url_reducer_core_member_register:
    pattern:  /register
    defaults: { _controller: UrlReducerCoreBundle:Member:register }
#
url_reducer_core_member:
    pattern:  /menu
    defaults: { _controller: UrlReducerCoreBundle:Member:Menu }

url_reducer_core_member_account:
    pattern:  /member/menu
    defaults: { _controller: UrlReducerCoreBundle:Member:memberMenu }

url_reducer_core_member_url_list:
    pattern:  /member/url/list
    defaults: { _controller: UrlReducerCoreBundle:Url:list }

# Must be the last route declared to not match each static urls
url_reducer_core_url_go:
    pattern:  /{sUrl}
    defaults: { _controller: UrlReducerCoreBundle:Url:goToSourceUrl }

