url_reducer_core_phpinfo:
    pattern:  /phpinfo
    defaults: { _controller: UrlReducerCoreBundle:Default:phpinfo }

url_reducer_core_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UrlReducerCoreBundle:Default:index }

url_reducer_core_index:
    pattern:  /
    defaults: { _controller: UrlReducerCoreBundle:Url:generateReducedUrl }

url_reducer_core_gogogo:
    pattern:  /{sUrl}
    defaults: { _controller: UrlReducerCoreBundle:Url:goToSourceUrl }

url_reducer_core_login:
    pattern:  /login
    defaults: { _controller: UrlReducerCoreBundle:Member:login }